insert into role_privilege (role, privilege) values ('Doctor', 'Add Encounters');
insert into role_privilege (role, privilege) values ('Doctor', 'Add Observations');
insert into role_privilege (role, privilege) values ('Doctor', 'Add Orders');
insert into role_privilege (role, privilege) values ('Doctor', 'Add Patient Identifiers');
insert into role_privilege (role, privilege) values ('Doctor', 'Add Patients');
insert into role_privilege (role, privilege) values ('Doctor', 'Add People');
insert into role_privilege (role, privilege) values ('Doctor', 'Add Visits');
insert into role_privilege (role, privilege) values ('Doctor', 'app:adt');
insert into role_privilege (role, privilege) values ('Doctor', 'app:clinical');
insert into role_privilege (role, privilege) values ('Doctor', 'app:document-upload');
insert into role_privilege (role, privilege) values ('Doctor', 'app:emergency');
insert into role_privilege (role, privilege) values ('Doctor', 'app:radiologyOrders');
insert into role_privilege (role, privilege) values ('Doctor', 'app:registration');
insert into role_privilege (role, privilege) values ('Doctor', 'Delete Orders');
insert into role_privilege (role, privilege) values ('Doctor', 'Delete Patients');
insert into role_privilege (role, privilege) values ('Doctor', 'Delete Visits');
insert into role_privilege (role, privilege) values ('Doctor', 'Discharge Summary');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Encounters');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Observations');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Orders');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Patient Identifiers');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Patients');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit People');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Users');
insert into role_privilege (role, privilege) values ('Doctor', 'Edit Visits');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Demographics Section');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Encounters Section');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Forms Section');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Graphs Section');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Overview Section');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Patient Summary');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Regimen Section');
insert into role_privilege (role, privilege) values ('Doctor', 'Patient Dashboard - View Visits Section');
insert into role_privilege (role, privilege) values ('Doctor', 'View Concept Classes');
insert into role_privilege (role, privilege) values ('Doctor', 'View Concept Datatypes');
insert into role_privilege (role, privilege) values ('Doctor', 'View Concept Map Types');
insert into role_privilege (role, privilege) values ('Doctor', 'View Concept Reference Terms');
insert into role_privilege (role, privilege) values ('Doctor', 'View Concept Sources');
insert into role_privilege (role, privilege) values ('Doctor', 'View Concepts');
insert into role_privilege (role, privilege) values ('Doctor', 'View Encounter Roles');
insert into role_privilege (role, privilege) values ('Doctor', 'View Encounter Types');
insert into role_privilege (role, privilege) values ('Doctor', 'View Encounters');
insert into role_privilege (role, privilege) values ('Doctor', 'View Locations');
insert into role_privilege (role, privilege) values ('Doctor', 'View Observations');
insert into role_privilege (role, privilege) values ('Doctor', 'View Order Types');
insert into role_privilege (role, privilege) values ('Doctor', 'View Orders');
insert into role_privilege (role, privilege) values ('Doctor', 'View Patient Identifiers');
insert into role_privilege (role, privilege) values ('Doctor', 'View Patients');
insert into role_privilege (role, privilege) values ('Doctor', 'View People');
insert into role_privilege (role, privilege) values ('Doctor', 'View Person Attribute Types');
insert into role_privilege (role, privilege) values ('Doctor', 'View Privileges');
insert into role_privilege (role, privilege) values ('Doctor', 'View Providers');
insert into role_privilege (role, privilege) values ('Doctor', 'View RESTWS');
insert into role_privilege (role, privilege) values ('Doctor', 'View Roles');
insert into role_privilege (role, privilege) values ('Doctor', 'View Users');
insert into role_privilege (role, privilege) values ('Doctor', 'View Visit Attribute Types');
insert into role_privilege (role, privilege) values ('Doctor', 'View Visit Types');
insert into role_privilege (role, privilege) values ('Doctor', 'View Visits');
insert into role_privilege (role, privilege) values ('Doctor', 'app:clinical:history');
insert into role_privilege (role, privilege) values ('Doctor', 'app:clinical:diagnosisTab');
insert into role_privilege (role, privilege) values ('Doctor', 'app:clinical:dispositionTab');
insert into role_privilege (role, privilege) values ('Doctor', 'app:clinical:observationTab');
insert into role_privilege (role, privilege) values ('Doctor', 'app:clinical:consultationTab');
insert into role_privilege (role, privilege) values ('Doctor', 'Manage Encounter Roles');

insert into role_privilege (role, privilege) values ('Nurse', 'Add Encounters');
insert into role_privilege (role, privilege) values ('Nurse', 'Add Observations');
insert into role_privilege (role, privilege) values ('Nurse', 'Add Orders');
insert into role_privilege (role, privilege) values ('Nurse', 'Add Patient Identifiers');
insert into role_privilege (role, privilege) values ('Nurse', 'Add Patients');
insert into role_privilege (role, privilege) values ('Nurse', 'Add People');
insert into role_privilege (role, privilege) values ('Nurse', 'Add Visits');
insert into role_privilege (role, privilege) values ('Nurse', 'app:adt');
insert into role_privilege (role, privilege) values ('Nurse', 'app:clinical');
insert into role_privilege (role, privilege) values ('Nurse', 'app:document-upload');
insert into role_privilege (role, privilege) values ('Nurse', 'app:emergency');
insert into role_privilege (role, privilege) values ('Nurse', 'app:radiologyOrders');
insert into role_privilege (role, privilege) values ('Nurse', 'app:registration');
insert into role_privilege (role, privilege) values ('Nurse', 'Delete Orders');
insert into role_privilege (role, privilege) values ('Nurse', 'Delete Patients');
insert into role_privilege (role, privilege) values ('Nurse', 'Delete Visits');
insert into role_privilege (role, privilege) values ('Nurse', 'Discharge Summary');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Encounters');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Observations');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Orders');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Patient Identifiers');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Patients');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit People');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Users');
insert into role_privilege (role, privilege) values ('Nurse', 'Edit Visits');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Demographics Section');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Encounters Section');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Forms Section');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Graphs Section');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Overview Section');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Patient Summary');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Regimen Section');
insert into role_privilege (role, privilege) values ('Nurse', 'Patient Dashboard - View Visits Section');
insert into role_privilege (role, privilege) values ('Nurse', 'View Concept Classes');
insert into role_privilege (role, privilege) values ('Nurse', 'View Concept Datatypes');
insert into role_privilege (role, privilege) values ('Nurse', 'View Concept Map Types');
insert into role_privilege (role, privilege) values ('Nurse', 'View Concept Reference Terms');
insert into role_privilege (role, privilege) values ('Nurse', 'View Concept Sources');
insert into role_privilege (role, privilege) values ('Nurse', 'View Concepts');
insert into role_privilege (role, privilege) values ('Nurse', 'View Encounter Roles');
insert into role_privilege (role, privilege) values ('Nurse', 'View Encounter Types');
insert into role_privilege (role, privilege) values ('Nurse', 'View Encounters');
insert into role_privilege (role, privilege) values ('Nurse', 'View Locations');
insert into role_privilege (role, privilege) values ('Nurse', 'View Observations');
insert into role_privilege (role, privilege) values ('Nurse', 'View Order Types');
insert into role_privilege (role, privilege) values ('Nurse', 'View Orders');
insert into role_privilege (role, privilege) values ('Nurse', 'View Patient Identifiers');
insert into role_privilege (role, privilege) values ('Nurse', 'View Patients');
insert into role_privilege (role, privilege) values ('Nurse', 'View People');
insert into role_privilege (role, privilege) values ('Nurse', 'View Person Attribute Types');
insert into role_privilege (role, privilege) values ('Nurse', 'View Privileges');
insert into role_privilege (role, privilege) values ('Nurse', 'View Providers');
insert into role_privilege (role, privilege) values ('Nurse', 'View RESTWS');
insert into role_privilege (role, privilege) values ('Nurse', 'View Roles');
insert into role_privilege (role, privilege) values ('Nurse', 'View Users');
insert into role_privilege (role, privilege) values ('Nurse', 'View Visit Attribute Types');
insert into role_privilege (role, privilege) values ('Nurse', 'View Visit Types');
insert into role_privilege (role, privilege) values ('Nurse', 'View Visits');
insert into role_privilege (role, privilege) values ('Nurse', 'app:clinical:observationTab');
insert into role_privilege (role, privilege) values ('Nurse', 'app:clinical:consultationTab');
insert into role_privilege (role, privilege) values ('Nurse', 'Manage Encounter Roles');

insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add Encounters');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add Observations');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add Orders');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add Patient Identifiers');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add Patients');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add People');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Add Visits');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'app:adt');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'app:clinical');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'app:document-upload');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'app:emergency');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'app:radiologyOrders');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'app:registration');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Delete Orders');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Delete Patients');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Delete Visits');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Discharge Summary');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Encounters');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Observations');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Orders');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Patient Identifiers');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Patients');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit People');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Users');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Edit Visits');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Demographics Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Encounters Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Forms Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Graphs Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Overview Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Patient Summary');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Regimen Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Patient Dashboard - View Visits Section');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Concept Classes');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Concept Datatypes');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Concept Map Types');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Concept Reference Terms');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Concept Sources');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Concepts');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Encounter Roles');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Encounter Types');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Encounters');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Locations');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Observations');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Order Types');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Orders');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Patient Identifiers');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Patients');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View People');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Person Attribute Types');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Privileges');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Providers');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View RESTWS');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Roles');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Users');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Visit Attribute Types');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Visit Types');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'View Visits');
insert into role_privilege (role, privilege) values ('PatientRecordManager', 'Manage Encounter Roles');